# -*- coding: utf-8 -*-
"""Задача 2.4 В

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KYEFP5ra6MfpVmzie3oPmzM_u8vIwocr

## Задача 2.4 Пункт B.
##### Удалите восклицательный знак из конца строки. 
* remove("Hi!") == "Hi"
* remove("Hi!!!") == "Hi!!"
* remove("!Hi") == "!Hi"

def remove_last_em(s):
    pass
"""

def remove_last_em(s):
    if s[-1] == "!":
        s = s[:-1]
    return s
print(remove_last_em("Hi!"))    # Hi
print(remove_last_em("Hi!!!"))  # Hi!!
print(remove_last_em("!Hi"))    # !Hi