# -*- coding: utf-8 -*-
"""untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/anna12gl/c8cf88fa1935f60bd898b9fee64a08b7/untitled3.ipynb
"""

str = "my_favorite_songs= Waste Moment Staying, Alive, A Sorta Fairytale, Start Me Up, New Salvation"
print (len(str))
print(str [-93:-54])
print(str [-93:-75] + str [-14:])
print(str [-93:-75] + str [-53:-47])
print(str [-93:-75] + str [-27:-15])