# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iLRF3n2yn93NiMFAZhCyuvB_PpC0U9Ye

## Пункт B. 
### Есть словарь песен 
### Распечатайте общее время звучания трех случайных песен
### Вывод: Три песни звучат ХХХ минут.
"""

import random
my_favorite_songs_dict= {
    'Waste a Moment': 3.03,
    'New Salvation': 4.02,
    'Staying\' Alive': 3.40,
    'Out of Touch': 3.03,
    'A Sorta Fairytale': 5.28,
    'Easy': 4.15,
    'Beautiful Day': 4.04,
    'Nowhere to Run': 2.58,
    'In This World': 4.02}
songs = random.sample(my_favorite_songs_dict.keys(), 3)
total_time = sum([my_favorite_songs_dict[song] for song in songs])
print(f"Три песни звучат {total_time:.2f} минут.")

9