# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rtYU4xLnUu7Cs1ip87Q8vC2UJkZhJ_LT

## Задача 1.2. пункт C.
#### Сгенерируйте случайные песни с помощью модуля random
#### import random
"""

import random
my_favorite_songs = [
    ['Waste a Moment', 3.03],
    ['New Salvation', 4.02],
    ['Staying\' Alive', 3.40],
    ['Out of Touch', 3.03],
    ['A Sorta Fairytale', 5.28],
    ['Easy', 4.15],
    ['Beautiful Day', 4.04],
    ['Nowhere to Run', 2.58],
    ['In This World', 4.02]]
songs = random.sample(my_favorite_songs, 3)
print ("Рандомный поиcк 3-х случайных песен  из списка x: ", songs)