# -*- coding: utf-8 -*-
"""Задача 2.4 А

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IDu6akEE89FWkCSu-iN6OPe8d2oXBlzB

##Задача 2.4.
#####Пункт A.
######## Напишите функцию, которая удаляет все восклицательные знаки из заданной строк.
* Например,
* foo("Hi! Hello!") -> "Hi Hello"
* foo("") -> ""
* foo("Oh, no!!!") -> "Oh, no"

def remove_exclamation_marks(s):
    pass
"""

def remove_exclamation_marks(s):
  return s.replace('!', '')

print(remove_exclamation_marks("Hi! Hello!"))
print(remove_exclamation_marks(""))
print(remove_exclamation_marks("Oh, no!!!"))